#aws:
#  region: "default"
#  accessKeyId: "root"
#  secretAccessKey: "root123!"
#  s3Endpoint: "http://minio.minio:9000"

image: ssup2/hive-metastore:4.0.1-0.1.6
imagePullSecret: ""

resources:
  requests:
    cpu: "500m"
    memory: "1024Mi"
  limits:
    cpu: "1000m"
    memory: "2048Mi"

schema:
  init: false # set true to initialize the database, false to use existing database
  dbType: postgres

config: |
  <configuration>
    <property>
      <name>fs.s3a.access.key</name>
      <value>root</value>
    </property>
    <property>
      <name>fs.s3a.secret.key</name>
      <value>root123!</value>
    </property>
    <property>
      <name>fs.s3a.endpoint</name>
      <value>minio.minio:9000</value>
    </property>
    <property>
      <name>fs.s3a.impl</name>
      <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
    </property>
    <property>
      <name>fs.s3a.connection.ssl.enabled</name>
      <value>false</value>
    </property>
    <property>
      <name>fs.s3a.fast.upload</name>
      <value>true</value>
    </property>
    <property>
      <name>fs.s3a.path.style.access</name>
      <value>true</value>
    </property>
    <property>
      <name>javax.jdo.option.ConnectionDriverName</name>
      <value>org.postgresql.Driver</value>
      <description>Driver class name for a JDBC metastore</description>
    </property>
    <property>
      <name>javax.jdo.option.ConnectionURL</name>
      <value>jdbc:postgresql://postgresql.postgresql:5432/metastore</value>
      <description>JDBC connect string for a JDBC metastore</description>
    </property>
    <property>
      <name>javax.jdo.option.ConnectionUserName</name>
      <value>postgres</value>
      <description>Username to use against metastore database</description>
    </property>
    <property>
      <name>javax.jdo.option.ConnectionPassword</name>
      <value>root123!</value>
      <description>Password to use against metastore database</description>
    </property>
  </configuration>

nodeSelector:
  node-group.dp.ssup2: "worker"

replicas: 1
