apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: hive-metastore
spec:
  type: LoadBalancer
  ports:
    - port: 9083
      protocol: TCP
      targetPort: 9083
  selector:
    app: hive-metastore
  sessionAffinity: None
